/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group_page;
import java.util.ArrayList;
import v1.Group_utils;
import javax.swing.DefaultListModel;
import static v1.Group_utils.getMemDetails;
import java.awt.Component;
import v1.Leader;
/**
 *
 * @author Dylan Ritchings
 */
import javax.swing.JComponent;
import javax.swing.JPanel;
public final class GroupPage extends javax.swing.JFrame {
    int groupID;
    ArrayList<String> id;
    ArrayList<String> forename;
    ArrayList<String> surname;
    ArrayList<String> email;
    ArrayList<String> tasksDone;

    ArrayList<String> taskID;
    ArrayList<String> taskTitle;
    ArrayList<String> taskStart;
    ArrayList<String> taskEnd;
    ArrayList<String> taskDesc;
    ArrayList<String> taskComp;
    
    
    
    
    /**
     * Creates new form GroupPage
     */
    public GroupPage() {
        this.groupID = 123;
        
        ArrayList<ArrayList<String>> memDetails = Group_utils.getMemDetails(groupID);
        this.id = memDetails.get(0);
        this.forename = memDetails.get(1);
        this.surname = memDetails.get(2);
        this.email = memDetails.get(3);
        this.tasksDone = memDetails.get(4);
        
        ArrayList<ArrayList<String>> taskDetails = Group_utils.getTaskDetails(groupID);
        System.out.println(taskDetails);
        this.taskID = taskDetails.get(0);
        this.taskTitle = taskDetails.get(1);
        this.taskStart = taskDetails.get(2);
        this.taskEnd = taskDetails.get(3);
        this.taskDesc = taskDetails.get(4);
        this.taskComp = taskDetails.get(5);
        initComponents();
        
        DefaultListModel memberLm = new DefaultListModel();
        String [] members = getMemNames(groupID);
        for (String member : members) {
            System.out.println(member);
            memberLm.addElement(member);
        }
        
        memberList.setModel(memberLm);
        removeMember.setEnabled(false); 
        
        Integer count = 0;
        JPanel  taskPanel = new TaskView(taskID.get(count), taskTitle.get(count), taskStart.get(count), taskEnd.get(count), taskDesc.get(count), taskComp.get(count));
        taskPane.add(taskPanel);
        add(taskPane,taskPanel);
    }
    

        /**
     * Creates an array containing names of people in a group.
     * @param groupID
     * @return memNames
     */
     public String[] getMemNames(int groupID)
    {
        
        //ArrayList<String> memNames = new ArrayList<>();
       
        String memNames[] = new String[forename.size()];
        for (int x = 0; x < forename.size(); x++)
        {
            String fName = forename.get(x);
            String sName = surname.get(x);
            
            //MemberList.addElement(fName + " " + sName);
            memNames[x]=(fName + " " + sName);
            
        }
        return memNames;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        memberList = new javax.swing.JList<String>();
        removeMember = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        taskPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        memberList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "test1" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        memberList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memberListFocusGained(evt);
            }
        });
        memberList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(memberList);

        removeMember.setText("Remove member");
        removeMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMemberActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Skills", "SQL", "Java", "Python", "HTML" }));

        jButton1.setText("Add Member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(taskPane, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeMember)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taskPane)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeMember)
                .addGap(18, 18, 18))
        );

        taskPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Removes a member from a group
     * @param evt 
     */
    private void removeMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMemberActionPerformed
        int memIndex = memberList.getSelectedIndex();
        Integer memID = Integer.valueOf(id.get(memIndex));
        Leader.deleteMember(memID, groupID);
        id.remove(memIndex);
        forename.remove(memIndex);
        surname.remove(memIndex); 
        email.remove(memIndex);
        tasksDone.remove(memIndex);
        memberLm.removeElement(memIndex);
        
    }//GEN-LAST:event_removeMemberActionPerformed

   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void memberListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memberListFocusGained
        removeMember.setEnabled(true); 
    }//GEN-LAST:event_memberListFocusGained

    private void memberListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberListMouseClicked

    }//GEN-LAST:event_memberListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> memberList;
    private javax.swing.JToggleButton removeMember;
    private javax.swing.JScrollPane taskPane;
    // End of variables declaration//GEN-END:variables
}
